name: generator_common
description: Common set of functions to get at parameters & class names for generating files
version: 1.0.0
#homepage: https://github.com/atreeon/typedef_for_fn

environment:  
  sdk: ">=2.12.0-0 <3.0.0"
  
dependencies:  
  analyzer: '>=0.40.0 <=1.0.0'
  analyzer_models: ^1.0.8
  build: ^1.6.3
  dartx: ^0.6.0
  quiver: ^3.0.0-nullsafety.3
  source_gen: ^0.9.10+3

dev_dependencies:  
  test: ^1.16.0-nullsafety.16
  