name: generator_common
description: Common set of functions to get at parameters & class names for generating files
version: 1.0.0-nullsafety8
homepage: https://github.com/atreeon/generator_common

environment:  
  sdk: ">=2.12.0-0 <3.0.0"
  
dependencies:
  analyzer: '>=1.7.0 <=3.0.0'
#  analyzer_models: ^1.0.8
  build: ^2.1.1
  dartx: ^0.6.0
  quiver: ^3.0.0-nullsafety.3
  source_gen: ^1.1.1

dev_dependencies:  
  test: ^1.18.2
  build_runner: ^2.1.4