name: generator_common
description: Common set of functions to get at parameters & class names for generating files
version: 1.2.1
homepage: https://github.com/atreeon/generator_common

environment:
  sdk: ">=3.1.3 <4.0.0"
  
dependencies:
  analyzer: '>=6.3.0 <=7.0.0'
#  analyzer_models: ^1.0.8
  build: ^2.1.1
  dartx: ^1.2.0
  quiver: ^3.0.0-nullsafety.3
  source_gen: ^1.1.1

dev_dependencies:  
  test: ^1.24.3
  build_runner: ^2.3.3